apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
spec:
  project: default
  source:
    repoURL: https://github.com/Chandrikatck/budget-app-gitops.git
    targetRevision: HEAD
    path: app  #Pointing directly to the directory with your manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
