apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Chandrikatck/budget-app-gitops
  username: Chandrikatck
  password: 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