apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # base64 encoded 'postgres'
  POSTGRES_PASSWORD: c2VjdXJlcGFzc3dvcmQ=  # base64 encoded 'securepassword'
  POSTGRES_DB: YnVkZ2V0X2RhdGFiYXNl     # base64 encoded 'budget_database'
